### ISSUE TITLE
Issue getting this to work on Rancher

### ISSUE THREAD

**Issue by 2devnull** [rawmind0/alpine-kafka#7]
Keeps looping

```
8/5/2017 3:44:37 PM'kafka-service' process is not running
8/5/2017 3:44:37 PM'kafka-service' trying to restart
8/5/2017 3:44:37 PM'kafka-service' start: '/opt/kafka/bin/kafka-service.sh start'
8/5/2017 3:45:07 PM'kafka-service' failed to start (exit status 0) -- '/opt/kafka/bin/kafka-service.sh start': Sat Aug 5 19:44:37 UTC 2017 - [ Starting kafka... ]
8/5/2017 3:45:07 PMSat Aug 5 19:44:37 UTC 2017 - [ Checking kafka configuration... ]
8/5/2017 3:45:07 PMSat Aug 5 19:44:37 UTC 2017 - [ Applying dinamic kafka configuration... ]
8/5/2017 3:45:07 PMSat Aug 5 19:44:37 UTC
8/5/2017 3:46:07 PM'kafka-service' process is not running
8/5/2017 3:46:07 PM'kafka-service' trying to restart
8/5/2017 3:46:07 PM'kafka-service' start: '/opt/kafka/bin/kafka-service.sh start'
8/5/2017 3:46:37 PM'kafka-service' failed to start (exit status 0) -- '/opt/kafka/bin/kafka-service.sh start': Sat Aug 5 19:46:07 UTC 2017 - [ Starting kafka... ]
8/5/2017 3:46:37 PMSat Aug 5 19:46:07 UTC 2017 - [ Checking kafka configuration... ]
8/5/2017 3:46:37 PMSat Aug 5 19:46:07 UTC 2017 - [ Applying dinamic kafka configuration... ]
8/5/2017 3:46:37 PMSat Aug 5 19:46:07 UTC
8/5/2017 3:47:37 PM'kafka-service' process is not running
8/5/2017 3:47:37 PM'kafka-service' trying to restart
8/5/2017 3:47:37 PM'kafka-service' start: '/opt/kafka/bin/kafka-service.sh start'
8/5/2017 3:48:08 PM'kafka-service' failed to start (exit status 0) -- '/opt/kafka/bin/kafka-service.sh start': Sat Aug 5 19:47:37 UTC 2017 - [ Starting kafka... ]
8/5/2017 3:48:08 PMSat Aug 5 19:47:37 UTC 2017 - [ Checking kafka configuration... ]
8/5/2017 3:48:08 PMSat Aug 5 19:47:37 UTC 2017 - [ Applying dinamic kafka configuration... ]
8/5/2017 3:48:08 PMSat Aug 5 19:47:37 UTC
8/5/2017 3:49:08 PM'kafka-service' process is not running
8/5/2017 3:49:08 PM'kafka-service' trying to restart
8/5/2017 3:49:08 PM'kafka-service' start: '/opt/kafka/bin/kafka-service.sh start'
8/5/2017 3:49:38 PM'kafka-service' failed to start (exit status 0) -- '/opt/kafka/bin/kafka-service.sh start': Sat Aug 5 19:49:08 UTC 2017 - [ Starting kafka... ]
8/5/2017 3:49:38 PMSat Aug 5 19:49:08 UTC 2017 - [ Checking kafka configuration... ]
8/5/2017 3:49:38 PMSat Aug 5 19:49:08 UTC 2017 - [ Applying dinamic kafka configuration... ]
8/5/2017 3:49:38 PMSat Aug 5 19:49:08 UTC
```

**Comment by rawmind0** [comment]
Could you try with new release?? How are you deploying, from the community-catalog??

**Comment by raeesaa** [comment]
Even I am facing similar issue with alpine-kafka:1.0.0-2. I get above error when I add this service to existing stack (with sidekicks for config and volume), however running this via community catalog works fine.

**Comment by rawmind0** [comment]
Thanks for the info @raeesaa. If the community-catalog package is working fine, loop problems should be about config or the way of launching it. 

No more news neither any answer from @2devnull.

Closing, please reopen if it's needed.

**Comment by raeesaa** [comment]
Thank you for quick reply @rawmind0. What I did now is, I created a custom catalog by combining docker-compose and rancher-compose files for community kafka and zookeeper catalogs and tried to create stack using it but even in that case kafka container failed to start with above error. 

docker-compose.yml

```
version: '2'
volumes:
  zkconfig:
    driver: local
    per_container: true
  zkdata:
    driver: local
    per_container: true
  brokerdata:
    driver: local
    per_container: true
  brokerconfig:
    driver: local
    per_container: true
services:
  # Kafka container with sidekicks for configuration and volume
  kafka-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '10003'
      SERVICE_UID: '10003'
      SERVICE_VOLUME: /opt/kafka/logs
    links:
    - zookeeper:zookeeper
    network_mode: none
    volumes:
    - brokerdata:/opt/kafka/logs
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  kafka-conf:
    image: rawmind/rancher-kafka:0.11.0.0-1
    links:
    - zookeeper:zookeeper
    network_mode: none
    volumes:
    - brokerconfig:/opt/tools
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  kafka:
    image: rawmind/alpine-kafka:1.0.0-2
    environment:
      ADVERTISE_PUB_IP: 'false'
      CONFD_INTERVAL: '60'
      JVMFLAGS: -Xmx1024m -Xms1024m
      KAFKA_AUTO_CREATE_TOPICS: 'true'
      KAFKA_DELETE_TOPICS: 'false'
      KAFKA_LOG_DIRS: /opt/kafka/logs
      KAFKA_LOG_RETENTION_HOURS: '168'
      KAFKA_NUM_PARTITIONS: '1'
      KAFKA_REPLICATION_FACTOR: '1'
      ZK_SERVICE: zookeeper
    links:
    - zookeeper:zookeeper
    tty: true
    volumes_from:
    - kafka-volume
    - kafka-conf
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: kafka-volume,kafka-conf
      io.rancher.container.hostname_override: container_name
  # Zookeeper container with sidekicks for configuration and volume
  zookeeper:
    tty: true
    image: rawmind/alpine-zk:3.4.10-0
    volumes_from:
      - zookeeper-volume
      - zookeeper-conf
    environment:
      - JVMFLAGS=-Xmx512m -Xms512m
      - CONFD_INTERVAL=60
      - ZK_DATA_DIR=/opt/zk/data
      - ZK_INIT_LIMIT=10
      - ZK_MAX_CLIENT_CXNS=500
      - ZK_SYNC_LIMIT=5
      - ZK_TICK_TIME=2000
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: zookeeper=true
      io.rancher.sidekicks: zookeeper-volume, zookeeper-conf
  zookeeper-conf:
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: zookeeper=true
      io.rancher.container.start_once: true
    image: rawmind/rancher-zk:3.4.9
    volumes:
      - zkconfig:/opt/tools
  zookeeper-volume:
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: zookeeper=true
      io.rancher.container.start_once: true
    environment:
      - SERVICE_UID=10002
      - SERVICE_GID=10002
      - SERVICE_VOLUME=/opt/zk/data
    volumes:
      - zkdata:/opt/zk/data
    image: rawmind/alpine-volume:0.0.2-1
```

rancher-compose.yml

```
version: '2'
.catalog:
  name: Kafka Zookeeper Catalog
  version: 0.0.1
  description: Kafka Zookeeper Catalog with scaling capabilities
  uuid: # Unique identifier to be used for upgrades. Please see note.
  minimum_rancher_version: 1.6.10
  questions: #Used to request user input for configuration options
services:
  kafka-volume:
    retain_ip: true
    scale: 2
    start_on_create: true
  kafka-conf:
    retain_ip: true
    scale: 2
    start_on_create: true
  kafka:
    retain_ip: true
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 9092
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
  zookeeper:
    retain_ip: true
    scale: 2
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 2181
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
  zookeeper-conf:
    retain_ip: true
    scale: 2
    start_on_create: true
  zookeeper-volume:
    retain_ip: true
    scale: 2
    start_on_create: true
```

I purposely hard-coded configurations in yml files instead of adding questions so that I could quickly test stuff. Can you please have a look at it and let me know if you find anything wrong with it? I have been struggling with this since morning.

Link to above catalog: https://bitbucket.org/raeesaa/kafka-zookeeper-catalog.git
